version: '2'

services:
  postgresql:
    container_name: taiga-postgres 
    restart: always
    image: postgres
    volumes:
    - /data/postgres:/var/lib/postgresql/data
    ports:
    - "5432"

  backend:
    container_name: taiga-back
    restart: always
    image: daprejean/taiga-back
    volumes:
    - taiga-media:/home/taiga/media
    - taiga-static:/home/taiga/static
    ports:
    - "8000:8000"
    links:
    - postgresql:postgres
    environment:
    - API_NAME=${API_NAME}
    - FRONT_NAME=${FRONT_NAME}
    - SECRET_KEY=${SECRET_KEY}
    - EMAIL_USE_TLS=${EMAIL_USE_TLS}
    - EMAIL_HOST=${EMAIL_HOST}
    - EMAIL_PORT=${EMAIL_PORT}
    - EMAIL_HOST_USER=${EMAIL_HOST_USER}
    - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}

  frontend:
    container_name: taiga-front
    restart: always
    image: daprejean/taiga-front
    volumes:
    - taiga-media:/home/taiga/media
    - taiga-static:/home/taiga/static
    ports:
    - "32221:80"
    - "32222:443"
    depends_on:
    - backend
    environment:
    - API_NAME=${API_NAME}

volumes:
  taiga-media:
  taiga-static:
